import clsx from 'clsx'

import { Roboto } from 'next/font/google'

import Header from '@/components/header'

import './globals.css'
import { NextAuthProvider } from './providers'

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'MyFavVault',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={clsx(roboto.className, 'noise-bg text-slate-800')}>
        <Header />
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}
